<?xml version="1.0" encoding="utf-8"?><Database Name="SWPlusDB" Class="SwPlusDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=pdmsrv;Initial Catalog=SWPlusDB;Persist Security Info=True;User ID=AirVentsCad" SettingsObjectName="DataBaseDomian.Properties.Settings" SettingsPropertyName="SWPlusDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="Materials.BendTable" Member="BendTables">
    <Type Name="BendTable">
      <Column Name="BendID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Thickness" Type="System.Decimal" DbType="Decimal(2,1) NOT NULL" CanBeNull="false" />
      <Column Name="[K-Factor]" Member="K_Factor" Type="System.Decimal" DbType="Decimal(5,3) NOT NULL" CanBeNull="false" />
      <Column Name="BendRadius" Type="System.Decimal" DbType="Decimal(4,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.View_Parts" Member="View_Parts">
    <Type Name="View_Part">
      <Column Name="Bend" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaintX" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaintY" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PaintZ" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SurfaceArea" Type="System.Decimal" DbType="Decimal(10,3) NOT NULL" CanBeNull="false" />
      <Column Name="Thickness" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Version" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="WorkpieceX" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="WorkpieceY" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="IDPDM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ConfigurationName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DXF" Type="System.String" DbType="VarChar(1) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.GetPath" Member="GetPaths">
    <Type Name="GetPath">
      <Column Name="DocumentID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Filename" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Path" Type="System.String" DbType="NVarChar(260)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.DXFCheck" Method="DXFCheck">
    <Parameter Name="IDPDM" Parameter="iDPDM" Type="System.Int32" DbType="Int" />
    <Parameter Name="Configuration" Parameter="configuration" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Version" Parameter="version" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.AirVents_AddPartOfPanel_test" Method="AirVents_AddPartOfPanel_test">
    <Parameter Name="PanelTypeID" Parameter="panelTypeID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ElementType" Parameter="elementType" Type="System.Int32" DbType="Int" />
    <Parameter Name="Width" Parameter="width" Type="System.Int32" DbType="Int" />
    <Parameter Name="Height" Parameter="height" Type="System.Int32" DbType="Int" />
    <Parameter Name="PartThick" Parameter="partThick" Type="System.Int32" DbType="Int" />
    <Parameter Name="PartMat" Parameter="partMat" Type="System.Int32" DbType="Int" />
    <Parameter Name="PartMatThick" Parameter="partMatThick" Type="System.Decimal" DbType="Decimal(3,1)" />
    <Parameter Name="Mirror" Parameter="mirror" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="StickyTape" Parameter="stickyTape" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="Step" Parameter="step" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="StepInsertion" Parameter="stepInsertion" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="Reinforcing" Parameter="reinforcing" Type="System.Boolean" DbType="Bit" />
    <Parameter Name="AirHole" Parameter="airHole" Type="System.String" DbType="NVarChar(255)" />
    <Parameter Name="PARTID" Parameter="pARTID" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>