<?xml version="1.0" encoding="utf-8"?><Database Name="SWPlusDB" Class="tbAssemblySpigotDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=pdmsrv;Initial Catalog=SWPlusDB;Persist Security Info=True;User ID=airventscad" SettingsObjectName="SolidWorksLibrary.Properties.Settings" SettingsPropertyName="SWPlusDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AssemblySpigot" Member="AssemblySpigots">
    <Type Name="AssemblySpigot">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="SpigotType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Width" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Height" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ElementType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="MaterialID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.AirVents_AddAssemblySpigot" Method="AirVents_AddAssemblySpigot">
    <Parameter Name="SpigotType" Parameter="spigotType" Type="System.Int32" DbType="Int" />
    <Parameter Name="Width" Parameter="width" Type="System.Int32" DbType="Int" />
    <Parameter Name="Height" Parameter="height" Type="System.Int32" DbType="Int" />
    <Parameter Name="ElementType" Parameter="elementType" Type="System.Int32" DbType="Int" />
    <Parameter Name="MaterialID" Parameter="materialID" Type="System.Int32" DbType="Int" />
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" Direction="InOut" />
    <Return Type="System.Int32" />
  </Function>
</Database>